/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AboutUsContent() {
  return (
    <article className="flex flex-col self-stretch my-auto min-w-[240px] w-[632px] max-md:max-w-full">
      <h1 className="text-4xl font-bold leading-tight text-black text-opacity-90 max-md:max-w-full">
        About Us
      </h1>
      <p className="mt-4 text-base leading-7 text-zinc-700 max-md:max-w-full">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu turpis
        molestie, dictum est a, mattis tellus. Sed dignissim, metus nec
        fringilla accumsan, risus sem sollicitudin lacus, ut interdum tellus
        elit sed risus. Maecenas eget condimentum velit, sit amet feugiat
        lectus. Class aptent taciti sociosqu ad litora torquent per conubia
        nostra, per inceptos himenaeos.
        <br />
        <br />
        Curabitur tempor quis eros tempus lacinia. Nam bibendum pellentesque
        quam a convallis. Sed ut vulputate nisi. Integer in felis sed leo
        vestibulum venenatis. Suspendisse quis arcu sem. Aenean feugiat ex eu
        vestibulum vestibulum. Morbi a eleifend magna. Nam metus lacus,
        porttitor eu mauris a, blandit ultrices nibh. Mauris sit amet magna non
        ligula vestibulum eleifend.
      </p>
    </article>
  );
}

export default AboutUsContent;
