/**
 * This code was generated by Builder.io.
 */
import React from "react";

function ContactForm() {
  return (
    <form className="flex flex-col flex-1 shrink text-base basis-0 min-w-[240px] text-black text-opacity-90 max-md:max-w-full">
      <p className="leading-relaxed text-zinc-700 max-md:max-w-full">
        Drop your message here
      </p>
      <div className="flex flex-col mt-4 w-full leading-snug max-md:max-w-full">
        <label htmlFor="name" className="max-md:max-w-full">
          Name
        </label>
        <input
          type="text"
          id="name"
          className="flex-1 shrink gap-2 self-stretch p-4 mt-2 w-full rounded-lg border border-solid border-black border-opacity-20 max-md:max-w-full"
          placeholder="UI Octve"
          aria-label="Name"
        />
      </div>
      <div className="flex flex-col mt-4 w-full leading-snug whitespace-nowrap max-md:max-w-full">
        <label htmlFor="email" className="max-md:max-w-full">
          Email
        </label>
        <input
          type="email"
          id="email"
          className="flex-1 shrink gap-2 self-stretch p-4 mt-2 w-full rounded-lg border border-solid border-black border-opacity-20 max-md:max-w-full"
          placeholder="UIOctve@examples.com"
          aria-label="Email"
        />
      </div>
      <div className="flex flex-col mt-4 w-full leading-snug max-md:max-w-full">
        <label htmlFor="message" className="max-md:max-w-full">
          Message
        </label>
        <textarea
          id="message"
          className="flex-1 shrink gap-2 px-4 pt-4 pb-28 mt-2 w-full rounded-lg border border-solid border-black border-opacity-20 min-h-[152px] max-md:pb-24 max-md:max-w-full"
          placeholder="Enter your message here"
          aria-label="Message"
        ></textarea>
      </div>
      <div className="mt-5"></div>
      <button
        type="submit"
        className="px-6 py-2 bg-pink-500 text-white hover:bg-pink-600 transition"
      >
          Submit
      </button>
    </form>
  );
}

export default ContactForm;
